// components/model-anatomy/index.js - generated by scripts/make-component.js.
// Kind: diagram. The "what is a model" artefact: a drifting cloud of raw text
// condenses into a latent network, gets ruled out as a lookup library, then
// fires a prediction and emits next-token probabilities.
//
// The beats are driven from OUTSIDE, by the host slide's own Reveal fragments.
// `class="fragment"` cannot work inside a shadow root (Reveal styles it as
// `.reveal .fragment` in its own sheet - see component-styles.md, "What does NOT
// cross the boundary"), so the component listens for Reveal's fragmentshown /
// fragmenthidden on its OWN <section> only and maps data-fragment-index -> step.
// Scoping to its own section is deliberate: a bare Reveal.on() listener fires for
// every slide in the deck.
//
//   step  -1  raw text drifting, no structure           (slide arrives)
//          0  it condenses into a latent network        (fragment 0)
//          1  ...but not a library you look things up in(fragment 1)
//          2  it predicts - pulse + token probabilities (fragment 2)
//
// GSAP earns its place for the two things CSS cannot express: the endless
// per-particle drift, and the one-shot pulse fired on entering step 2. Every
// step transition is a plain CSS transition keyed off `.stage[data-step]`,
// per gsap-hero.md's "one timeline, not many small tweens over many clicks".
import { DeckElement } from '@/components/deck-element.js';
import { SHARED_STYLES } from '@/components/shared-styles.js';
import { gsap } from '@/lib/gsap.js';

const VB = { w: 500, h: 400 };
const PULSE_LEN = 400;

// Decorative raw-training-data cloud (step -1). aria-hidden - the slide's own
// prose carries the meaning; this is texture.
const CLOUD_TEXT = [
	{ x: 110, y: 80, s: 'class Transformer(nn.Module):' },
	{ x: 268, y: 140, s: '"The quick brown fox"' },
	{ x: 78, y: 262, s: 'SELECT * FROM knowledge' },
	{ x: 312, y: 300, s: 'E = mc²' },
];
const CLOUD_DOTS = [
	{ cx: 200, cy: 180, r: 3, o: 0.6 },
	{ cx: 340, cy: 100, r: 4, o: 0.5 },
	{ cx: 150, cy: 320, r: 3, o: 0.7 },
	{ cx: 380, cy: 220, r: 5, o: 0.4 },
];

// Latent network (step 0+): edges, then nodes. `hub` = the one lit centre node,
// `out` = the lit output node the pulse arrives at.
const EDGES = [
	[100, 120, 250, 200],
	[100, 280, 250, 200],
	[250, 200, 400, 100],
	[250, 200, 400, 200],
	[250, 200, 400, 300],
];
const NODES = [
	{ cx: 100, cy: 120, r: 7 },
	{ cx: 100, cy: 280, r: 7 },
	{ cx: 250, cy: 200, r: 10, kind: 'hub' },
	{ cx: 400, cy: 100, r: 7, kind: 'dim' },
	{ cx: 400, cy: 200, r: 8, kind: 'out' },
	{ cx: 400, cy: 300, r: 7, kind: 'dim' },
];

const DEFAULT_TOKENS = 'predictor:82, engine:11, system:5, network:2';

/** "word:82, other:11" -> [{ word, pct }]. Silently drops malformed pairs. */
function parseTokens(raw) {
	return String(raw)
		.split(',')
		.map((pair) => {
			const at = pair.lastIndexOf(':');
			if (at < 0) return null;
			const word = pair.slice(0, at).trim();
			const pct = parseFloat(pair.slice(at + 1));
			return word && Number.isFinite(pct) ? { word, pct } : null;
		})
		.filter(Boolean);
}

/** Runs fn once window.Reveal exists (main.js sets it after deck.initialize()). */
function whenReveal(fn) {
	if (window.Reveal) return fn(window.Reveal);
	const t = setInterval(() => {
		if (window.Reveal) {
			clearInterval(t);
			fn(window.Reveal);
		}
	}, 30);
	return () => clearInterval(t);
}

function svgAttrs(o) {
	return Object.entries(o)
		.map(([k, v]) => `${k}="${v}"`)
		.join(' ');
}

class DeckModelAnatomy extends DeckElement {
	static tag = 'deck-model-anatomy';

	static observedAttributes = ['step', 'tokens', 'readout-label'];

	static styles = `
		${SHARED_STYLES}
		:host { display: block; }

		/* .box.border supplies the frame; kill its page-flow margin and padding
		   so the diagram meets the edge, and tint the ground behind it. */
		.stage {
			position: relative;
			margin-block: 0;
			padding: 0;
			overflow: hidden;
			aspect-ratio: ${VB.w} / ${VB.h};
			background: color-mix(in srgb, var(--fg) 4%, var(--bg));
		}

		svg {
			position: absolute;
			inset: 0;
			width: 100%;
			height: 100%;
		}

		/* --- the three SVG layers, cross-faded by [data-step] ---------------- */
		/* fill/stroke must come from CSS: var() does NOT resolve inside an SVG
		   presentation attribute (svg-diagram.md). */
		.cloud text { fill: var(--muted); font-family: var(--font-code); font-size: 10px; }
		.cloud circle { fill: var(--primary); }

		#line-grad stop { stop-color: var(--primary); }

		.edge { stroke: url(#line-grad); stroke-width: 1.5; }
		.node { fill: var(--bg); stroke: var(--primary); stroke-width: 2; }
		.node.dim { stroke: var(--line); }
		.node.hub, .node.out { fill: var(--primary); stroke: var(--fg); }
		.pulse {
			fill: none;
			stroke: var(--primary);
			stroke-width: 3;
			stroke-dasharray: ${PULSE_LEN};
			stroke-dashoffset: ${PULSE_LEN};
		}
		.veto circle { fill: none; stroke: var(--danger); stroke-width: 2; stroke-dasharray: 4 4; }
		.veto line { stroke: var(--danger); stroke-width: 3; }

		.cloud, .grid, .veto {
			transform-box: fill-box;
			transform-origin: center;
			transition:
				opacity var(--motion-hero-duration) var(--motion-hero-ease),
				transform var(--motion-hero-duration) var(--motion-hero-ease);
		}
		.grid { opacity: 0; transform: scale(0.92); }
		.veto { opacity: 0; transform: scale(0.8); }

		.stage[data-step="0"] .cloud,
		.stage[data-step="1"] .cloud,
		.stage[data-step="2"] .cloud { opacity: 0.15; }

		.stage[data-step="0"] .grid,
		.stage[data-step="2"] .grid { opacity: 1; transform: none; }
		.stage[data-step="1"] .grid { opacity: 1; transform: scale(0.95); }

		.stage[data-step="1"] .veto { opacity: 1; transform: scale(1.1); }

		/* --- the token-probability readout ---------------------------------- */
		.readout {
			position: absolute;
			right: var(--space-gap);
			top: 50%;
			width: 42%;
			opacity: 0;
			transform: translate(0.6em, -50%);
			transition:
				opacity var(--motion-ui-duration) var(--motion-ui-ease),
				transform var(--motion-ui-duration) var(--motion-ui-ease);
		}
		.stage[data-step="2"] .readout { opacity: 1; transform: translate(0, -50%); }

		.readout .box { margin-block: 0; font-family: var(--font-code); font-size: 0.75em; }
		.readout .note { display: block; margin: 0 0 var(--space-gap); font-size: 0.85em; text-transform: uppercase; letter-spacing: 0.05em; }
		.tok + .tok { margin-top: var(--space-gap); }
		.tok .row { justify-content: space-between; flex-wrap: nowrap; margin-bottom: 0.2em; }
		.tok .word { font-weight: 400; }
		.tok.top .word { font-weight: 700; }

		/* .meter/.fill are SHARED_STYLES; the width is what [data-step] drives,
		   and .fill.muted is a local modifier on top of that vocabulary. */
		.meter > .fill { width: 0; }
		.meter > .fill.muted { background: var(--muted); }
		.stage[data-step="2"] .meter > .fill { width: var(--pct); }

		@media (prefers-reduced-motion: reduce) {
			.cloud, .grid, .veto, .readout, .meter > .fill { transition: none; }
		}
	`;

	render() {
		this._tokens = parseTokens(this.getAttribute('tokens') ?? DEFAULT_TOKENS);
		this._reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;

		const stage = document.createElement('div');
		stage.className = 'stage box border';
		stage.innerHTML = `${this._svg()}${this._readout()}`;
		this.shadowRoot.append(stage);

		this._stage = stage;
		this._pulse = stage.querySelector('.pulse');
		this._setStep(Number(this.getAttribute('step') ?? -1), false);

		this._startDrift();
		this._bindFragments();
	}

	_svg() {
		const text = CLOUD_TEXT.map((t) => `<text x="${t.x}" y="${t.y}">${t.s}</text>`).join('');
		const dots = CLOUD_DOTS.map((d) => `<circle ${svgAttrs({ cx: d.cx, cy: d.cy, r: d.r, opacity: d.o })}/>`).join('');
		const edges = EDGES.map(([x1, y1, x2, y2]) => `<line class="edge" ${svgAttrs({ x1, y1, x2, y2 })}/>`).join('');
		const nodes = NODES.map((n) => `<circle class="node ${n.kind ?? ''}" ${svgAttrs({ cx: n.cx, cy: n.cy, r: n.r })}/>`).join('');

		return `
			<svg viewBox="0 0 ${VB.w} ${VB.h}" role="img"
			     aria-label="A cloud of raw text condensing into a network that predicts a next word">
				<defs>
					<linearGradient id="line-grad" x1="0%" y1="0%" x2="100%" y2="0%">
						<stop offset="0%" stop-opacity="0.2"/>
						<stop offset="50%" stop-opacity="0.9"/>
						<stop offset="100%" stop-opacity="0.2"/>
					</linearGradient>
				</defs>
				<g class="cloud" aria-hidden="true">${text}${dots}</g>
				<g class="grid">
					${edges}
					<path class="pulse" d="M 100 280 L 250 200 L 400 200"/>
					${nodes}
				</g>
				<g class="veto">
					<circle cx="250" cy="200" r="45"/>
					<line x1="225" y1="175" x2="275" y2="225"/>
					<line x1="275" y1="175" x2="225" y2="225"/>
				</g>
			</svg>
		`;
	}

	_readout() {
		const label = this.getAttribute('readout-label') ?? 'Token probabilities';
		const rows = this._tokens
			.map(
				(t, i) => `
			<div class="tok ${i === 0 ? 'top' : ''}">
				<div class="row">
					<span class="word ${i === 0 ? 'text-primary' : 'text-muted'}">${t.word}</span>
					<span class="text-muted">${t.pct}%</span>
				</div>
				<div class="meter">
					<div class="fill ${i === 0 ? '' : 'muted'}" style="--pct: ${t.pct}%; transition-delay: ${i * 0.08}s"></div>
				</div>
			</div>`,
			)
			.join('');

		return `<div class="readout"><div class="box border compact">
			<span class="note">${label}</span>${rows}
		</div></div>`;
	}

	/* ------------------------------------------------------------------ steps */

	_setStep(next, animate = true) {
		const step = Math.max(-1, Math.min(2, Number.isFinite(next) ? next : -1));
		if (step === this._step) return;
		this._step = step;
		this._stage.dataset.step = String(step);
		if (step === 2 && animate) this._firePulse();
		if (step !== 2) this._resetPulse();
	}

	_firePulse() {
		if (this._reduced) return this._pulse.style.setProperty('stroke-dashoffset', '0');
		gsap.fromTo(
			this._pulse,
			{ strokeDashoffset: PULSE_LEN },
			{ strokeDashoffset: 0, duration: this._sec('--motion-hero-duration', 0.6) * 1.2, ease: 'power1.inOut' },
		);
	}

	_resetPulse() {
		gsap.killTweensOf(this._pulse);
		gsap.set(this._pulse, { strokeDashoffset: PULSE_LEN });
	}

	/* ----------------------------------------------------------- ambient drift */

	_startDrift() {
		if (this._reduced) return;
		// Tied to the deck's own motion feel rather than a literal second count:
		// a slow multiple of the hero duration, jittered per particle.
		const base = this._sec('--motion-hero-duration', 0.6);
		this._drift = gsap.to(this.shadowRoot.querySelectorAll('.cloud > *'), {
			x: 'random(-15, 15)',
			y: 'random(-15, 15)',
			duration: `random(${(base * 4).toFixed(2)}, ${(base * 7).toFixed(2)})`,
			repeat: -1,
			yoyo: true,
			ease: 'sine.inOut',
		});
	}

	/* -------------------------------------------------- Reveal fragment wiring */

	_bindFragments() {
		const section = this.closest('section');
		if (!section) return;

		this._stopPolling = whenReveal((Reveal) => {
			const idx = (el) => Number(el.getAttribute('data-fragment-index'));
			const shown = (e) => {
				if (section.contains(e.fragment) && Number.isFinite(idx(e.fragment))) this._setStep(idx(e.fragment));
			};
			const hidden = (e) => {
				if (section.contains(e.fragment) && Number.isFinite(idx(e.fragment))) this._setStep(idx(e.fragment) - 1);
			};
			// Deep link / overview / navigating back: fragment events do not
			// replay, so read the state Reveal has already applied to the DOM.
			const resync = () => {
				if (!section.contains(Reveal.getCurrentSlide())) return void this._drift?.pause();
				this._drift?.resume();
				this._syncFromDom(section);
			};

			Reveal.on('fragmentshown', shown);
			Reveal.on('fragmenthidden', hidden);
			Reveal.on('slidechanged', resync);
			Reveal.on('ready', resync);
			this._offReveal = () => {
				Reveal.off('fragmentshown', shown);
				Reveal.off('fragmenthidden', hidden);
				Reveal.off('slidechanged', resync);
				Reveal.off('ready', resync);
			};
			resync();
		});
	}

	_syncFromDom(section) {
		let step = -1;
		for (const el of section.querySelectorAll('.fragment.visible')) {
			const i = Number(el.getAttribute('data-fragment-index'));
			if (Number.isFinite(i) && i > step) step = i;
		}
		this._setStep(step, false);
	}

	/* --------------------------------------------------------------- utilities */

	/** A --motion-* custom property as seconds (authored in ms or s). */
	_sec(name, fallback) {
		const raw = this.cssVar(name);
		const v = parseFloat(raw);
		if (!raw || Number.isNaN(v)) return fallback;
		return raw.includes('ms') ? v / 1000 : v;
	}

	attributeChangedCallback(name, before, after) {
		if (!this._upgraded || before === after) return;
		if (name === 'step') return this._setStep(Number(after));
		this._drift?.kill();
		this._stopPolling?.();
		this._offReveal?.();
		this._step = undefined;
		this.shadowRoot.querySelectorAll('.stage').forEach((n) => n.remove());
		this.render();
	}
}

customElements.define(DeckModelAnatomy.tag, DeckModelAnatomy);
