// components/param-heat/index.js - generated by scripts/make-component.js.
// Kind: chart. Flesh out render() / static styles per the recipe printed below.
import { DeckElement } from '@/components/deck-element.js';
import { SHARED_STYLES } from '@/components/shared-styles.js';
// import { d3 } from '@/lib/d3.js';   // lazy libs only when actually needed
// import { gsap } from '@/lib/gsap.js';

class DeckParamHeat extends DeckElement {
	static tag = 'deck-param-heat';

	/** attributes that trigger a re-render when changed */
	static observedAttributes = [/* 'kind', 'label' */];

	static styles = `
		${SHARED_STYLES}
		.root {
			gap: var(--space-gap);
			border-radius: var(--radius-card);
			transition: opacity var(--motion-ui-duration) var(--motion-ui-ease);
		}
	`;

	render() {
		const root = document.createElement('div');
		root.className = 'root';
		root.textContent = this.getAttribute('label') ?? '';
		this.shadowRoot.append(root);
	}

	attributeChangedCallback() {
		if (!this._upgraded) return;
		this.shadowRoot.querySelectorAll('.root').forEach((n) => n.remove());
		this.render();
	}
}

customElements.define(DeckParamHeat.tag, DeckParamHeat);
