// components/training-bars/index.js - generated by scripts/make-component.js.
// Kind: chart. An evolving stacked bar of "what the model was trained on".
//
// Six click-through stages (the <deck-*> owns its own controls - a back/forward
// pair plus a tick rail that fills to show how far through you are):
//   0  what it knows, by area   one bar per ideas-map topic, height = idea count
//   1  where it came from       each bar split by source (web/books/code/ref), as textures
//   2  forget the source        textures drop away, solid bars again
//   3  every bar is thousands    each bar shatters into one slice per idea (lion, lioness...)
//   4  none of it is you         the whole wall drains to grey
//   5  except, maybe...          one slice in Arts relights - "your Year 7 art competition entry"
//
// Topic order, colours and idea counts come straight from the <deck-ideas-map>
// dataset so the bars read as the same body of knowledge the map shows. The
// per-topic source mix is illustrative, authored as `trainingSources` in that
// same dataset.json - an additive key the map's own loader ignores.
import { DeckElement } from '@/components/deck-element.js';
import { SHARED_STYLES } from '@/components/shared-styles.js';
import { d3 } from '@/lib/d3.js';
import rawDataset from '../ideas-map/dataset.json';

const VB = { w: 960, h: 620 };
const M = { top: 24, right: 26, bottom: 64, left: 46 };
const IW = VB.w - M.left - M.right;
const IH = VB.h - M.top - M.bottom;

const STAGES = [
	'What it knows, by area',
	'Drawn from the web, books, code, reference works',
	'Forget where it came from for a second',
	'Every bar is really thousands of specific things',
	'…and none of it is you',
	'Except, maybe — the painting you entered in the Year 7 art competition',
];
const LAST = STAGES.length - 1;

// texture path per source, drawn in an 8x8 tile
const TEXTURES = [
	'M0,4 h8',                              // web        - horizontal rule
	'M4,0 v8',                              // books      - vertical rule
	'M-1,1 l3,-3 M0,8 l8,-8 M6,9 l3,-3',   // code       - forward diagonal
	'M0,0 l8,8 M8,0 l-8,8',                // reference  - crosshatch
];
// each source a slightly different tone, done with transparency so it tracks
// the deck theme: TEX_ALPHA fades the --fg texture strokes, TONE fades the
// topic-coloured fill itself - upper bands read lighter over the slide ground
const TEX_ALPHA = [0.3, 0.42, 0.54, 0.66];
const TONE = [1, 0.78, 0.6, 0.44];

let INSTANCE = 0;

function readTopics() {
	// first-seen `topic` across the node list, primary topic only - this is the
	// exact order <deck-ideas-map> derives, and the counts partition cleanly.
	const order = [];
	const count = new Map();
	for (const n of rawDataset.nodes || []) {
		const t = n.topic;
		if (t == null) continue;
		if (!count.has(t)) { count.set(t, 0); order.push(t); }
		count.set(t, count.get(t) + 1);
	}
	return order.map((id) => ({ id, count: count.get(id) }));
}

function titleCase(s) {
	return String(s).replace(/(^|[-_ ])(\w)/g, (_, b, c) => (b ? ' ' : '') + c.toUpperCase());
}

function darker(color, amount = 16) {
	const c = d3.hcl(color);
	if (!Number.isFinite(c.l)) return color;
	return d3.hcl(c.h, c.c, Math.max(c.l - amount, 0)).formatHex();
}

function semanticTopicColors(topicIds, resolve) {
	const series = [
		['--primary', '--primary-strong'],
		['--secondary', '--secondary-strong'],
		['--success'],
		['--warning'],
		['--danger'],
	];
	const out = new Map();
	topicIds.forEach((id, i) => {
		const [fillVar, strokeVar] = series[i % series.length];
		const fill = resolve(fillVar) || '#2563eb';
		out.set(id, { fill, stroke: resolve(strokeVar) || darker(fill) });
	});
	return out;
}

class DeckTrainingBars extends DeckElement {
	static tag = 'deck-training-bars';
	static observedAttributes = ['label', 'sliver'];

	static styles = `
		${SHARED_STYLES}
		:host {
			display: block;
			font-family: var(--font-body);
			color: var(--fg);
		}
		svg {
			display: block;
			margin-inline: auto;
			width: 100%;
			height: auto;
			max-width: 100%;
			max-height: var(--training-bars-max-h, 76vh);
			aspect-ratio: ${VB.w} / ${VB.h};
			overflow: visible;
		}
		svg text { paint-order: stroke; stroke: var(--bg); stroke-width: 2px; stroke-linejoin: round; }
		.grid line { stroke: var(--line); stroke-opacity: 0.4; shape-rendering: crispEdges; }
		.grid text { fill: var(--muted); font-family: var(--font-body); font-size: 11px; }
		.band-label { fill: var(--fg); font-family: var(--font-heading); font-size: 14px; font-weight: 600; }
		.node-label { fill: var(--fg); font-family: var(--font-body); font-size: 10px; font-weight: 500; pointer-events: none; }
		.layer.nodes rect { stroke: none; }
		.sliver.glow { filter: drop-shadow(0 0 6px var(--primary)); }
		.anno line { stroke: var(--primary); stroke-width: 1.5; }
		.anno text { fill: var(--fg); font-family: var(--font-heading); font-size: 13px; font-weight: 600; }
		.src-legend text { fill: var(--fg); font-family: var(--font-body); font-size: 11px; }
		.src-legend .lg-swatch { stroke: var(--line); }
		.src-legend .lg-back { fill: var(--bg); opacity: 0.92; stroke: var(--line); }
		.note.stage { display: block; margin-top: var(--space-block); min-height: 1.5em; text-align: right; font-style: italic; }
		.controls { display: flex; align-items: center; justify-content: center; gap: var(--space-inline); margin-top: var(--space-gap); }
		.ticks { display: flex; gap: 7px; }
		.tick { width: 24px; height: 4px; border-radius: var(--radius-round); background: var(--line); transition: background var(--motion-ui-duration) var(--motion-ui-ease); }
		.tick.on { background: var(--primary); }
		.nav { min-width: 2.6em; font-size: 1.1em; line-height: 1; }
	`;

	render() {
		this._uid = ++INSTANCE;
		this._topics = readTopics();
		const ids = this._topics.map((t) => t.id);
		this._colors = semanticTopicColors(ids, (n) => this.cssVar(n));

		this._x = d3.scaleBand().domain(ids).range([0, IW]).padding(0.28);
		this._y = d3.scaleLinear().domain([0, d3.max(this._topics, (t) => t.count)]).nice().range([IH, 0]);

		const ts = rawDataset.trainingSources || {};
		const src = ts.sources || [];
		const mix = ts.byTopic || {};
		this._sources = src;

		const label = this.getAttribute('label') || 'What the model was trained on';
		const svg = d3.select(this.shadowRoot).append('svg')
			.attr('viewBox', `0 0 ${VB.w} ${VB.h}`)
			.attr('role', 'img')
			.attr('aria-label', label)
			.attr('preserveAspectRatio', 'xMidYMid meet');
		svg.append('title').text(label);

		const defs = svg.append('defs');
		const texStroke = this.cssVar('--fg') || '#0a0b0e';
		src.forEach((s, i) => {
			defs.append('pattern')
				.attr('id', `tb-${this._uid}-${s.id}`)
				.attr('patternUnits', 'userSpaceOnUse')
				.attr('width', 8).attr('height', 8)
				.append('path')
				.attr('d', TEXTURES[i % TEXTURES.length])
				.attr('stroke', texStroke).attr('stroke-width', 1)
				.attr('stroke-opacity', TEX_ALPHA[i % TEX_ALPHA.length]).attr('fill', 'none');
		});
		const clipId = `tb-clip-${this._uid}`;
		defs.append('clipPath').attr('id', clipId).append('rect')
			.attr('x', -2).attr('y', -6).attr('width', IW + 4).attr('height', IH + 12);

		const plot = svg.append('g').attr('transform', `translate(${M.left},${M.top})`);

		// quiet gridlines instead of a full axis - a few horizontal rules + a
		// small count label at the left, no domain path, no tick marks
		const grid = plot.append('g').attr('class', 'grid');
		const ticks = this._y.ticks(4);
		grid.selectAll('line').data(ticks).join('line')
			.attr('x1', 0).attr('x2', IW)
			.attr('y1', (d) => this._y(d)).attr('y2', (d) => this._y(d));
		grid.selectAll('text').data(ticks).join('text')
			.attr('x', -10).attr('y', (d) => this._y(d))
			.attr('text-anchor', 'end').attr('dominant-baseline', 'middle')
			.text((d) => d);

		plot.append('g').attr('class', 'band-labels')
			.attr('transform', `translate(0,${IH})`)
			.selectAll('text').data(this._topics).join('text')
			.attr('class', 'band-label')
			.attr('text-anchor', 'end')
			.attr('transform', (d) => `translate(${this._x(d.id) + this._x.bandwidth() / 2},20) rotate(-28)`)
			.text((d) => titleCase(d.id));

		this._gTopics = plot.append('g').attr('class', 'layer topics');
		this._gSources = plot.append('g').attr('class', 'layer sources');
		this._gNodes = plot.append('g').attr('class', 'layer nodes').attr('clip-path', `url(#${clipId})`);
		this._gLegend = plot.append('g').attr('class', 'src-legend').attr('transform', 'translate(2,2)').attr('opacity', 0);
		this._gAnno = plot.append('g').attr('class', 'anno').attr('opacity', 0);

		// stage 0 / 2 - one flat topic-coloured bar per topic (same fill the
		// ideas-map gives that topic's nodes, with its darker shade as a hairline)
		this._gTopics.selectAll('rect').data(this._topics).join('rect')
			.attr('x', (d) => this._x(d.id))
			.attr('width', this._x.bandwidth())
			.attr('y', (d) => this._y(d.count))
			.attr('height', (d) => IH - this._y(d.count))
			.attr('rx', 3).attr('ry', 3)
			.attr('fill', (d) => this._colors.get(d.id).fill)
			.attr('stroke', 'none');

		// stage 1 - each bar stacked by source, base fill + texture overlay
		const segs = [];
		for (const t of this._topics) {
			const ratios = mix[t.id] || src.map(() => 1 / Math.max(src.length, 1));
			const total = d3.sum(ratios) || 1;
			let acc = 0;
			src.forEach((s, i) => {
				const v0 = acc;
				const v1 = acc + (ratios[i] / total) * t.count;
				acc = v1;
				segs.push({ key: `${t.id}|${s.id}`, topic: t.id, src: s.id, si: i, v0, v1 });
			});
		}
		const place = (sel, cls, fill) => sel.attr('class', cls)
			.attr('x', (d) => this._x(d.topic)).attr('width', this._x.bandwidth())
			.attr('y', (d) => this._y(d.v1)).attr('height', (d) => this._y(d.v0) - this._y(d.v1))
			.attr('fill', fill);
		const seg = this._gSources.selectAll('g.seg').data(segs, (d) => d.key).join('g').attr('class', 'seg');
		place(seg.append('rect'), 'seg-base', (d) => this._colors.get(d.topic).fill)
			.attr('fill-opacity', (d) => TONE[d.si % TONE.length])
			.attr('stroke', 'none');
		place(seg.append('rect'), 'seg-tex', (d) => `url(#tb-${this._uid}-${d.src})`);

		// stage 3+ - one unit-height slice per idea
		const nodes = [];
		const perTopic = new Map();
		for (const n of rawDataset.nodes || []) {
			const t = n.topic;
			if (t == null) continue;
			const i = perTopic.get(t) || 0;
			perTopic.set(t, i + 1);
			nodes.push({ key: n.id, id: n.id, name: n.name || n.id, topic: t, i });
		}
		this._nodes = nodes;
		const sliceH = this._y(0) - this._y(1);
		this._gNodes.selectAll('rect').data(nodes, (d) => d.key).join('rect')
			.attr('x', (d) => this._x(d.topic))
			.attr('width', this._x.bandwidth())
			.attr('y', (d) => this._y(d.i + 1))
			.attr('height', Math.max(sliceH - 1.5, 1))
			.attr('rx', 1.5).attr('ry', 1.5)
			.attr('fill', (d) => this._colors.get(d.topic).fill)
			.append('title').text((d) => d.name);

		this._gNodeLabels = this._gNodes.append('g').attr('class', 'node-labels');
		this._gNodeLabels.selectAll('text').data(nodes, (d) => d.key).join('text')
			.attr('class', 'node-label')
			.attr('x', (d) => this._x(d.topic) + 5)
			.attr('y', (d) => this._y(d.i + 0.5))
			.attr('dominant-baseline', 'middle')
			.attr('opacity', 0)
			.text((d) => d.name);

		// source legend (stage 1 only)
		this._gLegend.append('rect').attr('class', 'lg-back').attr('rx', 5)
			.attr('x', -4).attr('y', -4).attr('width', 186).attr('height', src.length * 19 + 8);
		const lgRow = this._gLegend.selectAll('g.lg-row').data(src).join('g')
			.attr('class', 'lg-row').attr('transform', (d, i) => `translate(0,${i * 19})`);
		lgRow.append('rect').attr('class', 'lg-swatch').attr('width', 14).attr('height', 14).attr('rx', 2)
			.attr('fill', (d) => `url(#tb-${this._uid}-${d.id})`);
		lgRow.append('text').attr('x', 21).attr('y', 11).text((d) => d.label || titleCase(d.id));

		this._annoLine = this._gAnno.append('line');
		// this._annoText = this._gAnno.append('text').attr('text-anchor', 'end')
		// 	.text('your Year 7 art competition entry');

		// controls
		const caption = document.createElement('p');
		caption.className = 'note stage';
		const controls = document.createElement('div');
		controls.className = 'controls';
		const prev = document.createElement('button');
		prev.className = 'btn ghost nav';
		prev.textContent = '‹';
		prev.setAttribute('aria-label', 'Previous stage');
		const next = document.createElement('button');
		next.className = 'btn ghost nav';
		next.textContent = '›';
		next.setAttribute('aria-label', 'Next stage');
		const ticks2 = document.createElement('div');
		ticks2.className = 'ticks';
		this._tickEls = STAGES.map(() => {
			const el = document.createElement('i');
			el.className = 'tick';
			ticks2.append(el);
			return el;
		});
		controls.append(prev, ticks2, next);
		this.shadowRoot.append(caption, controls);
		this._caption = caption;
		this._prev = prev;
		this._next = next;
		prev.addEventListener('click', () => this._go(this._stage - 1));
		next.addEventListener('click', () => this._go(this._stage + 1));

		this._stage = 0;
		this._apply(0, false);

		this._ro = new ResizeObserver(() => {
			this._colors = semanticTopicColors(ids, (n) => this.cssVar(n));
			this._gTopics.selectAll('rect').attr('stroke', (d) => this._colors.get(d.id).stroke);
			this._apply(this._stage, false);
		});
		this._ro.observe(this);
	}

	_go(target) {
		const n = Math.max(0, Math.min(LAST, target));
		if (n === this._stage) return;
		this._stage = n;
		this._apply(n, true);
	}

	_ms(name, fallback) {
		const raw = this.cssVar(name);
		if (!raw) return fallback;
		const v = parseFloat(raw);
		if (Number.isNaN(v)) return fallback;
		return raw.includes('ms') ? v : v * 1000;
	}

	_sliverId() {
		const wanted = this.getAttribute('sliver');
		if (wanted && this._nodes.some((n) => n.id === wanted)) return wanted;
		const art = this._nodes.find((n) => n.topic === 'arts' && n.id === 'painting')
			|| this._nodes.find((n) => n.topic === 'arts');
		return art ? art.id : (this._nodes[0] && this._nodes[0].id);
	}

	_apply(stage, animate) {
		const dur = animate ? this._ms('--motion-ui-duration', 200) * 2.4 : 0;
		const T = (sel) => sel.transition().duration(dur).ease(d3.easeCubicInOut);

		const showTopics = stage === 0 || stage === 2;
		T(this._gTopics).attr('opacity', showTopics ? 1 : 0);
		T(this._gSources).attr('opacity', stage === 1 ? 1 : 0);
		T(this._gNodes).attr('opacity', stage >= 3 ? 1 : 0);
		T(this._gLegend).attr('opacity', stage === 1 ? 1 : 0);

		const grey = this.cssVar('--muted') || '#888';
		const primary = this.cssVar('--primary') || '#2563eb';
		const sliverId = this._sliverId();
		T(this._gNodes.selectAll('rect')).attr('fill', (d) => {
			if (stage <= 3) return this._colors.get(d.topic).fill;
			if (stage === 5 && d.id === sliverId) return primary;
			return grey;
		});
		this._gNodes.selectAll('rect')
			.classed('sliver', (d) => d.id === sliverId)
			.classed('glow', (d) => stage === 5 && d.id === sliverId);
		T(this._gNodeLabels.selectAll('text')).attr('opacity', stage === 3 ? 0.9 : 0);

		const sliver = this._nodes.find((n) => n.id === sliverId);
		if (this._annoText && sliver) {
			const sx = this._x(sliver.topic) + this._x.bandwidth();
			const sy = this._y(sliver.i + 0.5);
			const tx = Math.min(sx + 100, IW);
			this._annoLine.attr('x1', sx).attr('y1', sy).attr('x2', tx).attr('y2', sy - 44);
			this._annoText.attr('x', tx).attr('y', sy - 50);
		}
		T(this._gAnno).attr('opacity', stage === 5 && this._annoText && sliver ? 1 : 0);

		this._caption.textContent = STAGES[stage];
		this._prev.disabled = stage === 0;
		this._next.disabled = stage === LAST;
		this._tickEls.forEach((el, i) => el.classList.toggle('on', i <= stage));
	}

	attributeChangedCallback() {
		if (!this._upgraded) return;
		const keep = this._stage || 0;
		this._ro?.disconnect();
		this.shadowRoot.querySelectorAll('svg, .note.stage, .controls').forEach((n) => n.remove());
		this.render();
		this._stage = keep;
		this._apply(keep, false);
	}
}

customElements.define(DeckTrainingBars.tag, DeckTrainingBars);
